spring:
  datasource:
    username: sa
    password: "{cipher}AYCWCLmShNr+kQYg/KyHhUoA4xXQEQe3VsZ+9v1knR7C4hO2r04EveGmnI/EDCwUz6q4W9cuarrsRu1vXOkav85a3BL2e8S0JJASOGjoHE4EXGTrp2VGJf593czs6ehy3aXgiR016e0Czl2IgUXWGeLaPGXodKFNZBz2oIHl/yMsjzzZHDIL5G37RZCk/f8ujXl0rLzBYPS18Lpg0ectLnaZOqTjHw08thxAbzIrH7lqH65ka1JHulpRWtSAno2mJOzTjCoKVU1BZ/bnOkW/dwX0UrAtPdNhP3aXPp+0ooGjny31zL9v7NQAxmJSGs0mPApTlmmxxErXKbejVPbcbjhQU5sry40NlsLnZkdchPjbqedp2W5HgudMTx8O3SpDHtld0bNdZQtOeH7kxxGnU1vpL80L8TUQbJL5THjsqua8uSz6H0+jHL3ZdVPD55M7UPFygk+6+J9Ef/iAmCVi2NS39Gpm9Uc7m/xzXcr7Og9BdZJBUJ7glVfhcYw4cOqAn2p8IB4bX00VrNXHMdo5ZxDmCmfj92B+jxA22yPwuJbzgNfT6uuMbruG75TO/t5CUJVBHQ/vSbjBkVnHwpEoMLA0"
# 모든 마이크로서비스 공통 토큰 설정
token:
  expiration-time: 86400000
  secret: my-very-long-secret-key-1234567890123456
