spring:
  datasource:
    username: sa
    password: "{cipher}AYANmqwy6I/QlU6lq0aOlFtpZrCoJ3xMnhPd+SPi+XLVV1tFvPM+sD6bZOdMir3dWhh6ZTEuRGzvze98koJpjoG6ivFy1esx4zo34q70RNaCbYgZ0eY29apiiPtM+5r9qDyRh4rqf829QnbCbu2lfKUUi6fO1gZcHmdmBKJBgWAaDhAD+Fjy8yKXTnBZEkyjGwAg8/j+qTwS6hixYFHu8sLkxIZNHnLkxAIga+PwM01i/JNY5AMmpaM2lkz4LEQdRjsp0MxC3i1gb82lzQfjYEY0pxL828nmBa3YOn2SQU76OsdoMiuQ4lYo2J9gVEkxLmNg61fZWR/5fTsr9INlL2w/UTKaWk13QMcxkmMDV293OW43qXbZrlh/zHgUBmHTbA64LMZGerxncMb4t1pfsAgcM3FqtVupira5KwZ/abdi3uPjHMAL6xu7fqFqGG7pem77eJbdhPuXDMkmx7C0vNKlE8VPpTLZliHEt7msFITimrkLqiTjDZRTKtoexf5Pki/jsntml9H50KwRcZuMQ/8tjVjWs6e+IHbNbUnFwnoTKA=="
# 모든 마이크로서비스 공통 토큰 설정
token:
  expiration-time: 86400000
  secret: my-very-long-secret-key-1234567890123456
