spring:
  datasource:
    username: sa
    password: "{cipher}AYBxdwWa7MXInWmYTAoOTxb/UdRM0Gz9XaAIa9gKQdIAwzs0dZqouWYz/f1hyVbFLPFaVRXtLCDDbeFce12ozCWuq8PdNDKIK7I0YeIQVZ6rj/+zWwfUZcf6V8kp7pA3Ot289gQ9uAgB0lCcIALE8XLNUtdcaJlygm5QWMtZzu0clddvJpWHiPTvnsw86Pl3g9a1ps3ozOcaGnWWDads6T9z0C1CmO5oXdyDkjRRlLNyQIiExhfNrAKCGBjOQzIwrs9mQ06F2pkrxmeJoHClTOjS+Akm1ocOm06gN0ObYOHn/vrw8+Mo10GMtdGwfSmvK4raU8sIXdh8/kLJLLX+uNv+mrOLen3tXzHIBWCxArTQzJcFF7DhO4l6dxywmTX2FojbJDm2XROFVl4LyyAyiXWV+254Q/4Sq48JBgmqglP5QKMZtjciCBK3hcNWPIrQEL76uW41LeBLh5EYFjRrBFVQlc4w8IVktpm5y/X2JWQp9pKLYmbC0XZR8F6aYp+HCvMMiOd2Z4vG1yaY1uEv6hevnZPtrv5bq+5GVZedwmdDLq6u4PXs+VQ4fLC6+vd+8Z1sQ/7+4Rh27fholbhd9LJswlQB2GDhvhkCW1eagqMZ0A=="
# 모든 마이크로서비스 공통 토큰 설정
token:
  expiration-time: 86400000
  secret: my-very-long-secret-key-1234567890123456
